-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 21:08:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Bodega_Campito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bodega_Campito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bodega_Campito` ;
USE `Bodega_Campito` ;

-- -----------------------------------------------------
-- Table `Bodega_Campito`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`Usuario` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`Trabajador` (
  `Nombre` VARCHAR(45) NOT NULL,
  `FK_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `fk_Trabajador_Usuario1_idx` (`FK_usuario` ASC),
  CONSTRAINT `fk_Trabajador_Usuario1`
    FOREIGN KEY (`FK_usuario`)
    REFERENCES `Bodega_Campito`.`Usuario` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`Bodega` (
  `Tipo_Bodega` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Tipo_Bodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`EncabezadoInvetarioBodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`EncabezadoInvetarioBodega` (
  `idEncabezadoInvetarioBodega` INT(20) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `FK_trabajador` VARCHAR(45) NOT NULL,
  `FK_Tipo_Bodega` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEncabezadoInvetarioBodega`),
  INDEX `fk_EncabezadoInvetarioBodega_Trabajador1_idx` (`FK_trabajador` ASC),
  INDEX `fk_EncabezadoInvetarioBodega_Bodega1_idx` (`FK_Tipo_Bodega` ASC),
  CONSTRAINT `fk_EncabezadoInvetarioBodega_Trabajador1`
    FOREIGN KEY (`FK_trabajador`)
    REFERENCES `Bodega_Campito`.`Trabajador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoInvetarioBodega_Bodega1`
    FOREIGN KEY (`FK_Tipo_Bodega`)
    REFERENCES `Bodega_Campito`.`Bodega` (`Tipo_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`Producto` (
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`Distribuidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`Distribuidores` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `FK_Usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `fk_Distribuidores_Usuario1_idx` (`FK_Usuario` ASC),
  CONSTRAINT `fk_Distribuidores_Usuario1`
    FOREIGN KEY (`FK_Usuario`)
    REFERENCES `Bodega_Campito`.`Usuario` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`DetalleInventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`DetalleInventario` (
  `idDetalleInventario` INT NOT NULL AUTO_INCREMENT,
  `FK_EncaDetalle` INT(20) NOT NULL,
  `FK_Producto` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  `FK_Propietario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetalleInventario`),
  INDEX `fk_DetalleInventario_Producto1_idx` (`FK_Producto` ASC),
  INDEX `fk_DetalleInventario_Usuario1_idx` (`FK_Propietario` ASC),
  INDEX `fk_DetalleInventario_EncabezadoInvetarioBodega1_idx` (`FK_EncaDetalle` ASC),
  CONSTRAINT `fk_DetalleInventario_Producto1`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `Bodega_Campito`.`Producto` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleInventario_Usuario1`
    FOREIGN KEY (`FK_Propietario`)
    REFERENCES `Bodega_Campito`.`Distribuidores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleInventario_EncabezadoInvetarioBodega1`
    FOREIGN KEY (`FK_EncaDetalle`)
    REFERENCES `Bodega_Campito`.`EncabezadoInvetarioBodega` (`idEncabezadoInvetarioBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`EncabezadoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`EncabezadoPedido` (
  `idPedido` INT(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `FK_Usuario` VARCHAR(45) NOT NULL,
  `FK_Trabajador` VARCHAR(45) NOT NULL,
  `FK_Tipo_Bodega` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_EncabezadoPedido_Usuario1_idx` (`FK_Usuario` ASC),
  INDEX `fk_EncabezadoPedido_Trabajador1_idx` (`FK_Trabajador` ASC),
  INDEX `fk_EncabezadoPedido_Bodega1_idx` (`FK_Tipo_Bodega` ASC),
  CONSTRAINT `fk_EncabezadoPedido_Usuario1`
    FOREIGN KEY (`FK_Usuario`)
    REFERENCES `Bodega_Campito`.`Distribuidores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPedido_Trabajador1`
    FOREIGN KEY (`FK_Trabajador`)
    REFERENCES `Bodega_Campito`.`Trabajador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPedido_Bodega1`
    FOREIGN KEY (`FK_Tipo_Bodega`)
    REFERENCES `Bodega_Campito`.`Bodega` (`Tipo_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`DetallePedido` (
  `idDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `FK_EncPedido` INT NOT NULL,
  `FK_Producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  INDEX `fk_DetallePedido_EncabezadoPedido1_idx` (`FK_EncPedido` ASC),
  INDEX `fk_DetallePedido_Producto1_idx` (`FK_Producto` ASC),
  CONSTRAINT `fk_DetallePedido_EncabezadoPedido1`
    FOREIGN KEY (`FK_EncPedido`)
    REFERENCES `Bodega_Campito`.`EncabezadoPedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_Producto1`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `Bodega_Campito`.`Producto` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`Prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`Prestador` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`EncabezadoPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`EncabezadoPrestamo` (
  `idPrestamo` INT(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `FK_trabajador` VARCHAR(45) NOT NULL,
  `FK_Propietario` VARCHAR(45) NOT NULL,
  `FK_Prestador` VARCHAR(45) NOT NULL,
  `FK_Tipo_Bodega` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_EncabezadoPrestamo_Pretador1_idx` (`FK_Prestador` ASC),
  INDEX `fk_EncabezadoPrestamo_Usuario1_idx` (`FK_Propietario` ASC),
  INDEX `fk_EncabezadoPrestamo_Trabajador1_idx` (`FK_trabajador` ASC),
  INDEX `fk_EncabezadoPrestamo_Bodega1_idx` (`FK_Tipo_Bodega` ASC),
  CONSTRAINT `fk_EncabezadoPrestamo_Pretador1`
    FOREIGN KEY (`FK_Prestador`)
    REFERENCES `Bodega_Campito`.`Prestador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPrestamo_Usuario1`
    FOREIGN KEY (`FK_Propietario`)
    REFERENCES `Bodega_Campito`.`Distribuidores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPrestamo_Trabajador1`
    FOREIGN KEY (`FK_trabajador`)
    REFERENCES `Bodega_Campito`.`Trabajador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPrestamo_Bodega1`
    FOREIGN KEY (`FK_Tipo_Bodega`)
    REFERENCES `Bodega_Campito`.`Bodega` (`Tipo_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`DetallePrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`DetallePrestamo` (
  `idDetallePrestamo` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `FK_EncPrestamo` INT NOT NULL,
  `FK_Producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetallePrestamo`),
  INDEX `fk_DetallePrestamo_EncabezadoPrestamo1_idx` (`FK_EncPrestamo` ASC),
  INDEX `fk_DetallePrestamo_Producto1_idx` (`FK_Producto` ASC),
  CONSTRAINT `fk_DetallePrestamo_EncabezadoPrestamo1`
    FOREIGN KEY (`FK_EncPrestamo`)
    REFERENCES `Bodega_Campito`.`EncabezadoPrestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePrestamo_Producto1`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `Bodega_Campito`.`Producto` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`EncabezadoDevoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`EncabezadoDevoluciones` (
  `idDevoluciones` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `FK_Trabajador` VARCHAR(45) NOT NULL,
  `FK_Propietario` VARCHAR(45) NOT NULL,
  `FK_Prestador` VARCHAR(45) NOT NULL,
  `FK_Bodega` VARCHAR(50) NOT NULL,
  INDEX `fk_Devoluciones_Usuario1_idx` (`FK_Propietario` ASC),
  INDEX `fk_Devoluciones_Pretador1_idx` (`FK_Prestador` ASC),
  INDEX `fk_Devoluciones_Bodega1_idx` (`FK_Bodega` ASC),
  PRIMARY KEY (`idDevoluciones`),
  INDEX `fk_EncabezadoDevoluciones_Trabajador1_idx` (`FK_Trabajador` ASC),
  CONSTRAINT `fk_Devoluciones_Usuario1`
    FOREIGN KEY (`FK_Propietario`)
    REFERENCES `Bodega_Campito`.`Distribuidores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devoluciones_Pretador1`
    FOREIGN KEY (`FK_Prestador`)
    REFERENCES `Bodega_Campito`.`Prestador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devoluciones_Bodega1`
    FOREIGN KEY (`FK_Bodega`)
    REFERENCES `Bodega_Campito`.`Bodega` (`Tipo_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoDevoluciones_Trabajador1`
    FOREIGN KEY (`FK_Trabajador`)
    REFERENCES `Bodega_Campito`.`Trabajador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`DetalleDevoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`DetalleDevoluciones` (
  `idDetalleDevoluciones` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `FK_EncDevoluciones` INT NOT NULL,
  `FK_Producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetalleDevoluciones`),
  INDEX `fk_DetalleDevoluciones_EncabezadoDevoluciones1_idx` (`FK_EncDevoluciones` ASC),
  INDEX `fk_DetalleDevoluciones_Producto1_idx` (`FK_Producto` ASC),
  CONSTRAINT `fk_DetalleDevoluciones_EncabezadoDevoluciones1`
    FOREIGN KEY (`FK_EncDevoluciones`)
    REFERENCES `Bodega_Campito`.`EncabezadoDevoluciones` (`idDevoluciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDevoluciones_Producto1`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `Bodega_Campito`.`Producto` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`EncabezadoPrestamo_respaldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`EncabezadoPrestamo_respaldo` (
  `idPrestamo_resp` INT(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `FK_trabajador` VARCHAR(45) NOT NULL,
  `FK_Propietario` VARCHAR(45) NOT NULL,
  `FK_Prestador` VARCHAR(45) NOT NULL,
  `FK_Tipo_Bodega` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPrestamo_resp`),
  INDEX `fk_EncabezadoPrestamo_Pretador1_idx` (`FK_Prestador` ASC),
  INDEX `fk_EncabezadoPrestamo_Usuario1_idx` (`FK_Propietario` ASC),
  INDEX `fk_EncabezadoPrestamo_Trabajador1_idx` (`FK_trabajador` ASC),
  INDEX `fk_EncabezadoPrestamo_Bodega1_idx` (`FK_Tipo_Bodega` ASC),
  CONSTRAINT `fk_EncabezadoPrestamo_Pretador10`
    FOREIGN KEY (`FK_Prestador`)
    REFERENCES `Bodega_Campito`.`Prestador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPrestamo_Usuario10`
    FOREIGN KEY (`FK_Propietario`)
    REFERENCES `Bodega_Campito`.`Distribuidores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPrestamo_Trabajador10`
    FOREIGN KEY (`FK_trabajador`)
    REFERENCES `Bodega_Campito`.`Trabajador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPrestamo_Bodega10`
    FOREIGN KEY (`FK_Tipo_Bodega`)
    REFERENCES `Bodega_Campito`.`Bodega` (`Tipo_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`DetallePrestamo_respaldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`DetallePrestamo_respaldo` (
  `idDetallePrestamo_resp` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `FK_EncPrestamo_Resp` INT(20) NOT NULL,
  `FK_Producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetallePrestamo_resp`),
  INDEX `fk_DetallePrestamo_Producto1_idx` (`FK_Producto` ASC),
  INDEX `fk_DetallePrestamo_respaldo_EncabezadoPrestamo_respaldo1_idx` (`FK_EncPrestamo_Resp` ASC),
  CONSTRAINT `fk_DetallePrestamo_Producto10`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `Bodega_Campito`.`Producto` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePrestamo_respaldo_EncabezadoPrestamo_respaldo1`
    FOREIGN KEY (`FK_EncPrestamo_Resp`)
    REFERENCES `Bodega_Campito`.`EncabezadoPrestamo_respaldo` (`idPrestamo_resp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`EncabezadoDevoluciones_respaldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`EncabezadoDevoluciones_respaldo` (
  `idDevoluciones` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `FK_Trabajador` VARCHAR(45) NOT NULL,
  `FK_Propietario` VARCHAR(45) NOT NULL,
  `FK_Prestador` VARCHAR(45) NOT NULL,
  `FK_Bodega` VARCHAR(50) NOT NULL,
  INDEX `fk_Devoluciones_Usuario1_idx` (`FK_Propietario` ASC),
  INDEX `fk_Devoluciones_Pretador1_idx` (`FK_Prestador` ASC),
  INDEX `fk_Devoluciones_Bodega1_idx` (`FK_Bodega` ASC),
  PRIMARY KEY (`idDevoluciones`),
  INDEX `fk_EncabezadoDevoluciones_Trabajador1_idx` (`FK_Trabajador` ASC),
  CONSTRAINT `fk_Devoluciones_Usuario10`
    FOREIGN KEY (`FK_Propietario`)
    REFERENCES `Bodega_Campito`.`Distribuidores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devoluciones_Pretador10`
    FOREIGN KEY (`FK_Prestador`)
    REFERENCES `Bodega_Campito`.`Prestador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devoluciones_Bodega10`
    FOREIGN KEY (`FK_Bodega`)
    REFERENCES `Bodega_Campito`.`Bodega` (`Tipo_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoDevoluciones_Trabajador10`
    FOREIGN KEY (`FK_Trabajador`)
    REFERENCES `Bodega_Campito`.`Trabajador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`DetalleDevoluciones_respaldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`DetalleDevoluciones_respaldo` (
  `idDetalleDevoluciones` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `FK_EncDevoluciones_Resp` INT NOT NULL,
  `FK_Producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetalleDevoluciones`),
  INDEX `fk_DetalleDevoluciones_Producto1_idx` (`FK_Producto` ASC),
  INDEX `fk_DetalleDevoluciones_respaldo_EncabezadoDevoluciones_resp_idx` (`FK_EncDevoluciones_Resp` ASC),
  CONSTRAINT `fk_DetalleDevoluciones_Producto10`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `Bodega_Campito`.`Producto` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDevoluciones_respaldo_EncabezadoDevoluciones_respal1`
    FOREIGN KEY (`FK_EncDevoluciones_Resp`)
    REFERENCES `Bodega_Campito`.`EncabezadoDevoluciones_respaldo` (`idDevoluciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`EncabezadoEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`EncabezadoEntrada` (
  `idEntrada` INT(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `FK_Usuario` VARCHAR(45) NOT NULL,
  `FK_Trabajador` VARCHAR(45) NOT NULL,
  `FK_Tipo_Bodega` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEntrada`),
  INDEX `fk_EncabezadoPedido_Usuario1_idx` (`FK_Usuario` ASC),
  INDEX `fk_EncabezadoPedido_Trabajador1_idx` (`FK_Trabajador` ASC),
  INDEX `fk_EncabezadoPedido_Bodega1_idx` (`FK_Tipo_Bodega` ASC),
  CONSTRAINT `fk_EncabezadoPedido_Usuario10`
    FOREIGN KEY (`FK_Usuario`)
    REFERENCES `Bodega_Campito`.`Distribuidores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPedido_Trabajador10`
    FOREIGN KEY (`FK_Trabajador`)
    REFERENCES `Bodega_Campito`.`Trabajador` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EncabezadoPedido_Bodega10`
    FOREIGN KEY (`FK_Tipo_Bodega`)
    REFERENCES `Bodega_Campito`.`Bodega` (`Tipo_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega_Campito`.`DetalleEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega_Campito`.`DetalleEntrada` (
  `idDetalle_Entrada` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `FK_encEntrada` INT(20) NOT NULL,
  `FK_Producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetalle_Entrada`),
  INDEX `fk_DetallePedido_Producto1_idx` (`FK_Producto` ASC),
  INDEX `fk_DetalleEntrada_EncabezadoEntrada1_idx` (`FK_encEntrada` ASC),
  CONSTRAINT `fk_DetallePedido_Producto10`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `Bodega_Campito`.`Producto` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleEntrada_EncabezadoEntrada1`
    FOREIGN KEY (`FK_encEntrada`)
    REFERENCES `Bodega_Campito`.`EncabezadoEntrada` (`idEntrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
